
/*
DROP TABLE PESSOA;
DROP TABLE CONTA;
DROP TABLE TRANSACAO;
*/

CREATE TABLE PESSOA (
	idPessoa			SERIAL PRIMARY KEY,
	nome				VARCHAR NOT NULL,
	cpf					VARCHAR NOT null,
	dataNascimento		DATE NOT NULL
);

CREATE TABLE CONTA (
	idConta				SERIAL PRIMARY KEY,
	idPessoa  			INT NOT NULL,
	saldo				NUMERIC(16,2) DEFAULT 0 NOT NULL,
	limiteSaqueDiario	NUMERIC(16,2) DEFAULT 0 NOT NULL,
	flagAtivo			char(1) DEFAULT 'S' NOT NULL,
	tipoConta			INT NOT NULL,
	dataCriacao			TIMESTAMP(6) NOT null,
	CONSTRAINT FkContaPessoa FOREIGN KEY(idPessoa) REFERENCES PESSOA(idPessoa) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TRANSACAO (
	idTransacao			SERIAL PRIMARY KEY,
	idConta  			INT NOT NULL,
	valor				NUMERIC(16,2) DEFAULT 0 NOT NULL,
	dataTransacao		TIMESTAMP(6) NOT null,
	CONSTRAINT FkTransacaoConta FOREIGN KEY(idConta) REFERENCES CONTA(idConta) ON DELETE CASCADE ON UPDATE CASCADE
);

insert into pessoa (NOME, CPF, dataNascimento) values ('TESTE', '12345678910', CURRENT_DATE);
